esphome:
  name: pixelbrain32
  friendly_name: PixelBrain32

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "PixelBrain32 Fallback"
    password: !secret ap_password

captive_portal:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO16          # adjust to your data output GPIO
    num_leds: 60         # adjust to your strip length
    name: "LED Strip"
    id: strip_light
    default_transition_length: 500ms
    restore_mode: ALWAYS_OFF   # prevents strip turning on after power loss or reboot

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: true
    name: "LED Toggle Button"
    on_press:
      then:
        - light.toggle: strip_light

  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: true
    name: "LED Brightness Button"
    on_multi_click:
      # Short press → brightness up 25%
      - timing:
          - ON for at most 350ms
          - OFF for at least 50ms
        then:
          - light.dim_relative:
              id: strip_light
              relative_brightness: 25%
              transition_length: 300ms
      # Long press → brightness down 25%
      - timing:
          - ON for at least 500ms
        then:
          - light.dim_relative:
              id: strip_light
              relative_brightness: -25%
              transition_length: 300ms
